openshift-pipelines/tektoncd-pipeline

upstream/go.mod
upstream/go.sum
upstream/vendor/modules.txt

Reverts openshift-pipelines/tektoncd-pipeline#389

Revert "fix(deps): update module github.com/containerd/containerd to v1.7.26"

---

.konflux/dockerfiles/entrypoint.Dockerfile

chore(KONFLUX-6210): fix and set name and cpe label for tektoncd-pipeline-1-14-entrypoint

---

.konflux/dockerfiles/events.Dockerfile

chore(KONFLUX-6210): fix and set name and cpe label for tektoncd-pipeline-1-14-events

---

.konflux/dockerfiles/sidecarlogresults.Dockerfile

chore(KONFLUX-6210): fix and set name and cpe label for tektoncd-pipeline-1-14-sidecarlogresults

---

.konflux/dockerfiles/workingdirinit.Dockerfile

chore(KONFLUX-6210): fix and set name and cpe label for tektoncd-pipeline-1-14-workingdirinit

---

.konflux/dockerfiles/entrypoint.Dockerfile

chore(KONFLUX-6210): fix and set name and cpe label for tektoncd-pipeline-1-15-entrypoint

---

.konflux/dockerfiles/nop.Dockerfile

chore(KONFLUX-6210): fix and set name and cpe label for tektoncd-pipeline-1-15-nop

---

.konflux/dockerfiles/resolvers.Dockerfile

chore(KONFLUX-6210): fix and set name and cpe label for tektoncd-pipeline-1-15-resolvers

---

.konflux/dockerfiles/sidecarlogresults.Dockerfile

chore(KONFLUX-6210): fix and set name and cpe label for tektoncd-pipeline-1-15-sidecarlogresults

---

.konflux/dockerfiles/webhook.Dockerfile

chore(KONFLUX-6210): fix and set name and cpe label for tektoncd-pipeline-1-15-webhook

---

.konflux/dockerfiles/controller.Dockerfile

chore(KONFLUX-6210): fix and set name and cpe label for tektoncd-pipeline-1-16-controller

---

.konflux/dockerfiles/entrypoint.Dockerfile

chore(KONFLUX-6210): fix and set name and cpe label for tektoncd-pipeline-1-16-entrypoint

---

.konflux/dockerfiles/events.Dockerfile

chore(KONFLUX-6210): fix and set name and cpe label for tektoncd-pipeline-1-16-events

---

.konflux/dockerfiles/nop.Dockerfile

chore(KONFLUX-6210): fix and set name and cpe label for tektoncd-pipeline-1-16-nop

---

.konflux/dockerfiles/resolvers.Dockerfile

chore(KONFLUX-6210): fix and set name and cpe label for tektoncd-pipeline-1-16-resolvers

---

.konflux/dockerfiles/controller.Dockerfile

chore(KONFLUX-6210): fix and set name and cpe label for tektoncd-pipeline-1-17-controller

---

.konflux/dockerfiles/webhook.Dockerfile

chore(KONFLUX-6210): fix and set name and cpe label for tektoncd-pipeline-1-17-webhook

---

.konflux/dockerfiles/workingdirinit.Dockerfile

chore(KONFLUX-6210): fix and set name and cpe label for tektoncd-pipeline-1-17-workingdirinit

---

.konflux/dockerfiles/controller.Dockerfile

chore(KONFLUX-6210): fix and set name and cpe label for tektoncd-pipeline-1-18-controller

---

.konflux/dockerfiles/events.Dockerfile

chore(KONFLUX-6210): fix and set name and cpe label for tektoncd-pipeline-1-18-events

---

.konflux/dockerfiles/nop.Dockerfile

chore(KONFLUX-6210): fix and set name and cpe label for tektoncd-pipeline-1-18-nop

---

.konflux/dockerfiles/resolvers.Dockerfile

chore(KONFLUX-6210): fix and set name and cpe label for tektoncd-pipeline-1-18-resolvers

---

.konflux/dockerfiles/webhook.Dockerfile

chore(KONFLUX-6210): fix and set name and cpe label for tektoncd-pipeline-1-18-webhook

---

.konflux/dockerfiles/controller.Dockerfile

chore(KONFLUX-6210): fix and set name and cpe label for tektoncd-pipeline-1-19-controller

---

.konflux/dockerfiles/nop.Dockerfile

chore(KONFLUX-6210): fix and set name and cpe label for tektoncd-pipeline-1-19-nop
